name: Azure_Project01_CI

on:
  push:
    branches:
      - status-badge
  workflow_dispatch:
    inputs:
      name:
        description: "Who are you"
        default: "name"


jobs:
    hello:
        runs-on: ubuntu-latest

        steps:
        - name: Hello Step
          run: echo "Hello ${{ github.event.inputs.name }}"
